services:
  mongo:
    container_name: rhombus
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_DB_ROOT_USERNAME: ${MONGO_DB_ROOT_USERNAME}
      MONGO_DB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
